# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/simulation_event_receiver.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#rpc/simulation_event_receiver.proto\"\xb8\x01\n\x12NotifyEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x36\n\nevent_args\x18\x03 \x03(\x0b\x32\".NotifyEventRequest.EventArgsEntry\x12\x12\n\ncommand_id\x18\x04 \x01(\x05\x1a\x30\n\x0e\x45ventArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x13NotifyEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12SyncCommandRequest\"\xc5\x01\n\x13SyncCommandResponse\x12\x13\n\x0bhas_command\x18\x01 \x01(\x08\x12\x12\n\ncommand_id\x18\x02 \x01(\x05\x12\x14\n\x0c\x63ommand_name\x18\x03 \x01(\t\x12;\n\x0c\x63ommand_args\x18\x04 \x03(\x0b\x32%.SyncCommandResponse.CommandArgsEntry\x1a\x32\n\x10\x43ommandArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8d\x01\n\x17SimulationEventReceiver\x12\x38\n\x0bNotifyEvent\x12\x13.NotifyEventRequest\x1a\x14.NotifyEventResponse\x12\x38\n\x0bSyncCommand\x12\x13.SyncCommandRequest\x1a\x14.SyncCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.simulation_event_receiver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYEVENTREQUEST_EVENTARGSENTRY']._options = None
  _globals['_NOTIFYEVENTREQUEST_EVENTARGSENTRY']._serialized_options = b'8\001'
  _globals['_SYNCCOMMANDRESPONSE_COMMANDARGSENTRY']._options = None
  _globals['_SYNCCOMMANDRESPONSE_COMMANDARGSENTRY']._serialized_options = b'8\001'
  _globals['_NOTIFYEVENTREQUEST']._serialized_start=40
  _globals['_NOTIFYEVENTREQUEST']._serialized_end=224
  _globals['_NOTIFYEVENTREQUEST_EVENTARGSENTRY']._serialized_start=176
  _globals['_NOTIFYEVENTREQUEST_EVENTARGSENTRY']._serialized_end=224
  _globals['_NOTIFYEVENTRESPONSE']._serialized_start=226
  _globals['_NOTIFYEVENTRESPONSE']._serialized_end=264
  _globals['_SYNCCOMMANDREQUEST']._serialized_start=266
  _globals['_SYNCCOMMANDREQUEST']._serialized_end=286
  _globals['_SYNCCOMMANDRESPONSE']._serialized_start=289
  _globals['_SYNCCOMMANDRESPONSE']._serialized_end=486
  _globals['_SYNCCOMMANDRESPONSE_COMMANDARGSENTRY']._serialized_start=436
  _globals['_SYNCCOMMANDRESPONSE_COMMANDARGSENTRY']._serialized_end=486
  _globals['_SIMULATIONEVENTRECEIVER']._serialized_start=489
  _globals['_SIMULATIONEVENTRECEIVER']._serialized_end=630
# @@protoc_insertion_point(module_scope)
