# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import simulator_pb2 as rpc_dot_simulator__pb2


class SimulatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEventReceiver = channel.unary_unary(
                '/Simulator/RegisterEventReceiver',
                request_serializer=rpc_dot_simulator__pb2.RegisterEventReceiverRequest.SerializeToString,
                response_deserializer=rpc_dot_simulator__pb2.RegisterEventReceiverResponse.FromString,
                )
        self.GetTimeStamp = channel.unary_unary(
                '/Simulator/GetTimeStamp',
                request_serializer=rpc_dot_simulator__pb2.GetTimeStampRequest.SerializeToString,
                response_deserializer=rpc_dot_simulator__pb2.GetTimeStampResponse.FromString,
                )
        self.GetNewCommandId = channel.unary_unary(
                '/Simulator/GetNewCommandId',
                request_serializer=rpc_dot_simulator__pb2.GetNewCommandIdRequest.SerializeToString,
                response_deserializer=rpc_dot_simulator__pb2.GetNewCommandIdResponse.FromString,
                )


class SimulatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterEventReceiver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeStamp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNewCommandId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEventReceiver': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEventReceiver,
                    request_deserializer=rpc_dot_simulator__pb2.RegisterEventReceiverRequest.FromString,
                    response_serializer=rpc_dot_simulator__pb2.RegisterEventReceiverResponse.SerializeToString,
            ),
            'GetTimeStamp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeStamp,
                    request_deserializer=rpc_dot_simulator__pb2.GetTimeStampRequest.FromString,
                    response_serializer=rpc_dot_simulator__pb2.GetTimeStampResponse.SerializeToString,
            ),
            'GetNewCommandId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNewCommandId,
                    request_deserializer=rpc_dot_simulator__pb2.GetNewCommandIdRequest.FromString,
                    response_serializer=rpc_dot_simulator__pb2.GetNewCommandIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Simulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterEventReceiver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/RegisterEventReceiver',
            rpc_dot_simulator__pb2.RegisterEventReceiverRequest.SerializeToString,
            rpc_dot_simulator__pb2.RegisterEventReceiverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimeStamp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/GetTimeStamp',
            rpc_dot_simulator__pb2.GetTimeStampRequest.SerializeToString,
            rpc_dot_simulator__pb2.GetTimeStampResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNewCommandId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Simulator/GetNewCommandId',
            rpc_dot_simulator__pb2.GetNewCommandIdRequest.SerializeToString,
            rpc_dot_simulator__pb2.GetNewCommandIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
