# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import simulation_event_receiver_pb2 as rpc_dot_simulation__event__receiver__pb2


class SimulationEventReceiverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyEvent = channel.unary_unary(
                '/SimulationEventReceiver/NotifyEvent',
                request_serializer=rpc_dot_simulation__event__receiver__pb2.NotifyEventRequest.SerializeToString,
                response_deserializer=rpc_dot_simulation__event__receiver__pb2.NotifyEventResponse.FromString,
                )
        self.SyncCommand = channel.unary_unary(
                '/SimulationEventReceiver/SyncCommand',
                request_serializer=rpc_dot_simulation__event__receiver__pb2.SyncCommandRequest.SerializeToString,
                response_deserializer=rpc_dot_simulation__event__receiver__pb2.SyncCommandResponse.FromString,
                )


class SimulationEventReceiverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationEventReceiverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyEvent,
                    request_deserializer=rpc_dot_simulation__event__receiver__pb2.NotifyEventRequest.FromString,
                    response_serializer=rpc_dot_simulation__event__receiver__pb2.NotifyEventResponse.SerializeToString,
            ),
            'SyncCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncCommand,
                    request_deserializer=rpc_dot_simulation__event__receiver__pb2.SyncCommandRequest.FromString,
                    response_serializer=rpc_dot_simulation__event__receiver__pb2.SyncCommandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SimulationEventReceiver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulationEventReceiver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimulationEventReceiver/NotifyEvent',
            rpc_dot_simulation__event__receiver__pb2.NotifyEventRequest.SerializeToString,
            rpc_dot_simulation__event__receiver__pb2.NotifyEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SimulationEventReceiver/SyncCommand',
            rpc_dot_simulation__event__receiver__pb2.SyncCommandRequest.SerializeToString,
            rpc_dot_simulation__event__receiver__pb2.SyncCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
