# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/submission_manager.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crpc/submission_manager.proto\"$\n\rSubmitRequest\x12\x13\n\x0bworking_dir\x18\x01 \x01(\t\"1\n\x0eSubmitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\x05\" \n\x1eGetStorageManagerConfigRequest\"\xad\x01\n\x1fGetStorageManagerConfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x38\n\x04\x61rgs\x18\x03 \x03(\x0b\x32*.GetStorageManagerConfigResponse.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"u\n\x0b\x44\x65scription\x12\x32\n\x0b\x64\x65scription\x18\x01 \x03(\x0b\x32\x1d.Description.DescriptionEntry\x1a\x32\n\x10\x44\x65scriptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x17SimulationSubmitRequest\x12%\n\x0fjob_description\x18\x01 \x01(\x0b\x32\x0c.Description\x12\'\n\x11task_descriptions\x18\x02 \x03(\x0b\x32\x0c.Description\"+\n\x18SimulationSubmitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xeb\x01\n\x11SubmissionManager\x12+\n\x06Submit\x12\x0e.SubmitRequest\x1a\x0f.SubmitResponse\"\x00\x12^\n\x17GetStorageManagerConfig\x12\x1f.GetStorageManagerConfigRequest\x1a .GetStorageManagerConfigResponse\"\x00\x12I\n\x10SimulationSubmit\x12\x18.SimulationSubmitRequest\x1a\x19.SimulationSubmitResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.submission_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE_ARGSENTRY']._options = None
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE_ARGSENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._options = None
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_options = b'8\001'
  _globals['_SUBMITREQUEST']._serialized_start=32
  _globals['_SUBMITREQUEST']._serialized_end=68
  _globals['_SUBMITRESPONSE']._serialized_start=70
  _globals['_SUBMITRESPONSE']._serialized_end=119
  _globals['_GETSTORAGEMANAGERCONFIGREQUEST']._serialized_start=121
  _globals['_GETSTORAGEMANAGERCONFIGREQUEST']._serialized_end=153
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE']._serialized_start=156
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE']._serialized_end=329
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE_ARGSENTRY']._serialized_start=286
  _globals['_GETSTORAGEMANAGERCONFIGRESPONSE_ARGSENTRY']._serialized_end=329
  _globals['_DESCRIPTION']._serialized_start=331
  _globals['_DESCRIPTION']._serialized_end=448
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_start=398
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_end=448
  _globals['_SIMULATIONSUBMITREQUEST']._serialized_start=450
  _globals['_SIMULATIONSUBMITREQUEST']._serialized_end=555
  _globals['_SIMULATIONSUBMITRESPONSE']._serialized_start=557
  _globals['_SIMULATIONSUBMITRESPONSE']._serialized_end=600
  _globals['_SUBMISSIONMANAGER']._serialized_start=603
  _globals['_SUBMISSIONMANAGER']._serialized_end=838
# @@protoc_insertion_point(module_scope)
