# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import submission_manager_pb2 as rpc_dot_submission__manager__pb2


class SubmissionManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/SubmissionManager/Submit',
                request_serializer=rpc_dot_submission__manager__pb2.SubmitRequest.SerializeToString,
                response_deserializer=rpc_dot_submission__manager__pb2.SubmitResponse.FromString,
                )
        self.GetStorageManagerConfig = channel.unary_unary(
                '/SubmissionManager/GetStorageManagerConfig',
                request_serializer=rpc_dot_submission__manager__pb2.GetStorageManagerConfigRequest.SerializeToString,
                response_deserializer=rpc_dot_submission__manager__pb2.GetStorageManagerConfigResponse.FromString,
                )
        self.SimulationSubmit = channel.unary_unary(
                '/SubmissionManager/SimulationSubmit',
                request_serializer=rpc_dot_submission__manager__pb2.SimulationSubmitRequest.SerializeToString,
                response_deserializer=rpc_dot_submission__manager__pb2.SimulationSubmitResponse.FromString,
                )


class SubmissionManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStorageManagerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulationSubmit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmissionManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=rpc_dot_submission__manager__pb2.SubmitRequest.FromString,
                    response_serializer=rpc_dot_submission__manager__pb2.SubmitResponse.SerializeToString,
            ),
            'GetStorageManagerConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStorageManagerConfig,
                    request_deserializer=rpc_dot_submission__manager__pb2.GetStorageManagerConfigRequest.FromString,
                    response_serializer=rpc_dot_submission__manager__pb2.GetStorageManagerConfigResponse.SerializeToString,
            ),
            'SimulationSubmit': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulationSubmit,
                    request_deserializer=rpc_dot_submission__manager__pb2.SimulationSubmitRequest.FromString,
                    response_serializer=rpc_dot_submission__manager__pb2.SimulationSubmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SubmissionManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SubmissionManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SubmissionManager/Submit',
            rpc_dot_submission__manager__pb2.SubmitRequest.SerializeToString,
            rpc_dot_submission__manager__pb2.SubmitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStorageManagerConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SubmissionManager/GetStorageManagerConfig',
            rpc_dot_submission__manager__pb2.GetStorageManagerConfigRequest.SerializeToString,
            rpc_dot_submission__manager__pb2.GetStorageManagerConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimulationSubmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SubmissionManager/SimulationSubmit',
            rpc_dot_submission__manager__pb2.SimulationSubmitRequest.SerializeToString,
            rpc_dot_submission__manager__pb2.SimulationSubmitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
