#!/bin/sh
export OMPI_ALLOW_RUN_AS_ROOT=1
export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
unset FOAM_SIGFPE
export FOAM_SIGFPE=0
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# NOTE: To launch without the runParallel, do the following:
#
#           mpirun -np $NPROCS simpleFoam -parallel
#
python3 setup.py # to make sure all processors have the same common starting point

rm -rf log.simpleFoam
runParallel simpleFoam &

python3 monitor.py

# ----------------------------------------------------------------- end-of-file
