# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eva_iterator/rpc/iterator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x65va_iterator/rpc/iterator.proto\"\x16\n\x14GetThroughputRequest\"K\n\x15GetThroughputResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05ready\x18\x02 \x01(\x08\x12\x12\n\nthroughput\x18\x03 \x01(\x02\"\x1d\n\x1bNotifySaveCheckpointRequest\"/\n\x1cNotifySaveCheckpointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa3\x01\n\x08Iterator\x12@\n\rGetThroughput\x12\x15.GetThroughputRequest\x1a\x16.GetThroughputResponse\"\x00\x12U\n\x14NotifySaveCheckpoint\x12\x1c.NotifySaveCheckpointRequest\x1a\x1d.NotifySaveCheckpointResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eva_iterator.rpc.iterator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETTHROUGHPUTREQUEST']._serialized_start=35
  _globals['_GETTHROUGHPUTREQUEST']._serialized_end=57
  _globals['_GETTHROUGHPUTRESPONSE']._serialized_start=59
  _globals['_GETTHROUGHPUTRESPONSE']._serialized_end=134
  _globals['_NOTIFYSAVECHECKPOINTREQUEST']._serialized_start=136
  _globals['_NOTIFYSAVECHECKPOINTREQUEST']._serialized_end=165
  _globals['_NOTIFYSAVECHECKPOINTRESPONSE']._serialized_start=167
  _globals['_NOTIFYSAVECHECKPOINTRESPONSE']._serialized_end=214
  _globals['_ITERATOR']._serialized_start=217
  _globals['_ITERATOR']._serialized_end=380
# @@protoc_insertion_point(module_scope)
